BÀI 1: LÀM QUEN VỚI PYTORCH

Bài 1. Tạo Tensor cơ bản

Tạo một Tensor số nguyên kích thước 2 × 3 và hiển thị kết quả.

In [2]:
import torch
a = torch.tensor(
    [[1, 2, 3],
    [4, 5, 6]],
    dtype=torch.int32
)
print(a)
print("Kích thước:", a.shape)
print("Số chiều:", a.ndim)
print("Kiểu dữ liệu:", a.dtype)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
Kích thước: torch.Size([2, 3])
Số chiều: 2
Kiểu dữ liệu: torch.int32


Bài 2. Tạo các Tensor thường dùng

Thực hành tạo Tensor ngẫu nhiên, Tensor toàn số 0, toàn số 1 và ma trận đơn vị.

In [3]:
import torch
a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)
print(a)
print(b)
print(c)
print(d)
print(e)
f = torch.full((5, 5), 10)
print(f)

tensor([[0.8276, 0.7342, 0.5786, 0.0160],
        [0.2951, 0.6270, 0.5161, 0.9284],
        [0.6495, 0.4536, 0.0916, 0.1507]])
tensor([[-1.2572,  0.0618,  0.5002,  0.4513],
        [ 1.1434,  0.2594, -0.5151,  2.1207],
        [ 1.2295,  1.4473,  1.8213, -0.2105]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])


Bài 3. Kiểm tra thông tin Tensor

Sử dụng shape, size(), ndim và dtype để kiểm tra các thuộc tính của Tensor.

In [5]:
import torch

a = torch.zeros(2, 3, 4)
print("Tensor: ")
print(a)
print("Shape", a.shape)
print("Size", a.size())
print("Number of dimesions:", a.ndim)
print("Data type:", a.dtype)

Tensor: 
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape torch.Size([2, 3, 4])
Size torch.Size([2, 3, 4])
Number of dimesions: 3
Data type: torch.float32


Bài 4. Slicing và Indexing 

Truy xuất một phần dữ liệu từ Tensor nhiều chiều.

In [ ]:
import torch
a = torch.randn(3, 4, 5)
print("Original tensor:")
print(a)
print("\nTensor a[1]:")
print(a[1])
print