BÀI 1: LÀM QUEN VỚI PYTORCH

Bài 1. Tạo Tensor cơ bản

In [2]:
import torch
a = torch.tensor(
    [[1, 2, 3],
    [4, 5, 6]],
    dtype=torch.int32
)
print(a)
print("Kích thước:", a.shape)
print("Số chiều:", a.ndim)
print("Kiểu dữ liệu:", a.dtype)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
Kích thước: torch.Size([2, 3])
Số chiều: 2
Kiểu dữ liệu: torch.int32


Bài 2. Tạo các Tensor thường dùng

In [1]:
import torch
a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)
print(a)
print(b)
print(c)
print(d)
print(e)
f = torch.full((5, 5), 10)
print(f)

tensor([[0.6730, 0.5658, 0.1200, 0.2300],
        [0.4576, 0.8843, 0.2477, 0.8836],
        [0.9410, 0.7618, 0.1547, 0.3102]])
tensor([[ 0.3303,  0.7853,  1.7568,  0.5948],
        [ 0.4336,  0.2728,  0.2165, -0.6887],
        [-1.1548, -1.0367, -1.0054,  0.1456]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])
